# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('outsource', '0092_auto_20180717_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourcingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='GUID')),
                ('start', models.DateField(verbose_name='Дата начала периода')),
                ('end', models.DateField(verbose_name='Дата окончания периода')),
                ('state', models.CharField(choices=[('accepted', 'Accepted'), ('ready', 'Ready')], default='accepted', max_length=8, verbose_name='Статус обработки')),
                ('dt_accepted', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('dt_ready', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('comments', models.CharField(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail адрес')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО пользователя')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство')),
                ('headquater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Запрос сотрудников у контрагента',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutsourcingShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID')),
                ('state', models.CharField(choices=[('wait', 'Wait'), ('accept', 'Accept'), ('reject', 'Reject'), ('delete', 'Delete')], default='wait', max_length=8, verbose_name='Состояние обработки смены')),
                ('start', models.DateTimeField(verbose_name='Начало смены')),
                ('end', models.DateTimeField(verbose_name='Окончание смены')),
                ('worktime', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рабочее время в минутах')),
                ('dt_change', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('start_date', models.DateField(null=True, verbose_name='День начала смены')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство')),
                ('agency_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.AgencyEmployee', verbose_name='Сотрудник')),
                ('headquater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Job', verbose_name='Функция')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shifts.OutsourcingRequest')),
            ],
            options={
                'verbose_name': 'Запрашиваемая смена',
                'verbose_name_plural': 'Запрашиваемые смены',
                'ordering': ['-start'],
            },
        ),
    ]
