# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='outsourcingrequest',
            table='outsource_outsourcingrequest',
        ),
        migrations.AlterModelTable(
            name='outsourcingshift',
            table='outsource_outsourcingshift',
        ),
    ]
