# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_auto_20180717_1605'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='outsourcingrequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='outsourcingshift',
            table=None,
        ),
    ]
