# Generated by Django 2.0.5 on 2018-09-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_auto_20180806_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outsourcingrequest',
            options={'ordering': ['-id'], 'verbose_name': 'Запрос на персонал', 'verbose_name_plural': 'Запросы на персонал'},
        ),
    ]
