"""
Copyright 2018 ООО «Верме»

Миграция базы данных приложения shifts
"""

# Generated by Django 2.0.5 on 2018-10-10 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20181009_1912'),
        ('outsource', '0105_auto_20181002_1756'),
        ('shifts', '0005_auto_20180919_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID')),
                ('state', models.CharField(choices=[('accept', 'Подтверждена'), ('delete', 'Удалена')], default='accept', max_length=120)),
                ('quota_number', models.IntegerField(verbose_name='Номер квоты')),
                ('start', models.DateTimeField(verbose_name='Начало смены')),
                ('end', models.DateTimeField(verbose_name='Окончание смены')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='День начала смены')),
                ('worktime', models.IntegerField(verbose_name='Рабочее время')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Подразделение промоутера')),
                ('agency_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.AgencyEmployee', verbose_name='Сотрудник')),
                ('aheadquarter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='aheadquarters', to='outsource.Headquater', verbose_name='Компания-промоутер')),
                ('headquarter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='headquarters', to='outsource.Headquater', verbose_name='Клиент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-id'],
            },
        ),
    ]
