# Generated by Django 2.0.5 on 2018-10-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_auto_20181011_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoshift',
            name='store_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.StoreArea', verbose_name='Зона магазина'),
        ),
    ]
