# Generated by Django 2.0.5 on 2018-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_auto_20181015_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoshift',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
