# Generated by Django 2.0.5 on 2018-11-06 10:03

import apps.lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_promoshift_dt_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoshift',
            name='end',
            field=models.DateTimeField(validators=[apps.lib.validators.validate_dtime_15m], verbose_name='Окончание смены'),
        ),
        migrations.AlterField(
            model_name='promoshift',
            name='start',
            field=models.DateTimeField(validators=[apps.lib.validators.validate_dtime_15m], verbose_name='Начало смены'),
        ),
    ]
