# Generated by Django 2.0.5 on 2018-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_auto_20181106_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsourcingrequest',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Причина отклонения'),
        ),
    ]
