# Generated by Django 2.0.5 on 2018-11-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_outsourcingrequest_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoshift',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='день'),
        ),
        migrations.AddField(
            model_name='promoshift',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='месяц'),
        ),
        migrations.AddField(
            model_name='promoshift',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='год'),
        ),
    ]
