# Generated by Django 2.0.5 on 2019-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_update_promoshift_year_month_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoshift',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='День начала смены'),
        ),
    ]
