# Generated by Django 2.0.5 on 2019-04-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0129_quotainfo'),
        ('shifts', '0014_auto_20190206_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoshift',
            name='quota_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.QuotaInfo', verbose_name='Информация о квоте'),
        ),
    ]
