# Generated by Django 2.0.5 on 2019-04-05 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_promoshift_quota_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoshift',
            name='dt_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Обновлена'),
            preserve_default=False,
        ),
    ]
