# Generated by Django 2.0.5 on 2019-04-16 08:09

import apps.lib.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0132_quotainfo_quota_number'),
        ('shifts', '0016_promoshift_dt_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID')),
                ('start_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='День начала доступности')),
                ('start', models.DateTimeField(validators=[apps.lib.validators.validate_dtime_15m], verbose_name='Начало доступности')),
                ('end', models.DateTimeField(validators=[apps.lib.validators.validate_dtime_15m], verbose_name='Окончание доступности')),
                ('dt_change', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Подразделение промоутера')),
                ('aheadquarter', models.ForeignKey(blank=True, limit_choices_to={'party': 'promo'}, on_delete=django.db.models.deletion.PROTECT, related_name='avail_aheadquarters', to='outsource.Headquater', verbose_name='Компания-промоутер')),
                ('headquarter', models.ForeignKey(blank=True, limit_choices_to={'party': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='avail_headquarters', to='outsource.Headquater', verbose_name='Клиент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Магазин')),
                ('store_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.StoreArea', verbose_name='Зона магазина')),
            ],
            options={
                'verbose_name': 'Доступность',
                'verbose_name_plural': 'Доступности',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='promoshift',
            name='dt_updated',
        ),
    ]
