# Generated by Django 2.0.5 on 2019-04-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0017_auto_20190416_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoshift',
            name='quota_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='outsource.QuotaInfo', verbose_name='Информация о квоте'),
        ),
    ]
