# Generated by Django 2.0.5 on 2019-05-07 12:38

import apps.lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0018_auto_20190422_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='start_date',
        ),
        migrations.AddField(
            model_name='availability',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(0, 'Не доступен'), (1, 'Доступен')], default=0, verbose_name='Тип доступности'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end',
            field=models.DateField(validators=[apps.lib.validators.validate_dtime_15m], verbose_name='Окончание доступности'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start',
            field=models.DateField(validators=[apps.lib.validators.validate_dtime_15m], verbose_name='Начало доступности'),
        ),
    ]
