# Generated by Django 2.0.5 on 2019-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0019_auto_20190507_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end',
            field=models.DateField(verbose_name='Окончание доступности'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start',
            field=models.DateField(verbose_name='Начало доступности'),
        ),
    ]
