# Generated by Django 2.0.5 on 2019-06-17 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0021_auto_20190606_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoshift',
            name='guid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='GUID'),
        ),
    ]
