# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourcingshift',
            name='agency_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.AgencyEmployee', verbose_name='Сотрудник'),
        ),
    ]
