# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-26 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0002_auto_20180125_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourcingrequest',
            name='dt_accepted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 26, 10, 4, 52, 833256, tzinfo=utc), verbose_name='Получен'),
            preserve_default=False,
        ),
    ]
