# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0004_auto_20180126_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название агентства')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Уникальный код агентства')),
            ],
        ),
    ]
