# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0005_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Агентство', 'verbose_name_plural': 'Справочник агентств'},
        ),
        migrations.AddField(
            model_name='outsourcingrequest',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
            preserve_default=False,
        ),
    ]
