# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0006_auto_20180216_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsourcingshift',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
