# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0007_outsourcingshift_dt_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourcingrequest',
            name='state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('ready', 'Ready')], default='accepted', max_length=8, verbose_name='Статус обработки заявки'),
        ),
        migrations.AlterField(
            model_name='outsourcingshift',
            name='state',
            field=models.CharField(choices=[('wait', 'Wait'), ('accept', 'Accept'), ('reject', 'Reject')], default='wait', max_length=8, verbose_name='Состояние обработки смены'),
        ),
    ]
