# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0008_auto_20180220_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourcingshift',
            name='state',
            field=models.CharField(choices=[('wait', 'Wait'), ('accept', 'Accept'), ('reject', 'Reject'), ('delete', 'Delete')], default='wait', max_length=8, verbose_name='Состояние обработки смены'),
        ),
    ]
