# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0011_outsourcingshift_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemployee',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
        ),
    ]
