# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0012_agencyemployee_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Дата назначения функции')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Дата окончания выполнения функции')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Job', verbose_name='Агентство')),
            ],
            options={
                'verbose_name': 'История назначений',
                'verbose_name_plural': 'История назначений',
                'ordering': ['-start'],
            },
        ),
        migrations.RemoveField(
            model_name='agencyemployee',
            name='agency',
        ),
        migrations.AddField(
            model_name='outsourcingshift',
            name='start_date',
            field=models.DateField(null=True, verbose_name='День начала смены'),
        ),
        migrations.AddField(
            model_name='agencyhistory',
            name='agency_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.AgencyEmployee'),
        ),
    ]
