# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0014_start_date_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyhistory',
            options={'ordering': ['-start'], 'verbose_name': 'История назначений агентств', 'verbose_name_plural': 'История назначений агентств'},
        ),
        migrations.AlterModelOptions(
            name='jobhistory',
            options={'ordering': ['-start'], 'verbose_name': 'История назначений функций', 'verbose_name_plural': 'История назначений функций'},
        ),
        migrations.AlterField(
            model_name='agencyhistory',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
        ),
        migrations.AlterField(
            model_name='agencyhistory',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания назначения агентства'),
        ),
        migrations.AlterField(
            model_name='agencyhistory',
            name='start',
            field=models.DateField(verbose_name='Дата назначения агентства'),
        ),
    ]
