# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def set_names(apps, schema_editor):
    AgencyEmployee = apps.get_model("outsource", "AgencyEmployee")
    for employee in AgencyEmployee.objects.all():
        fio = employee.name
        try:
            employee.surname = fio.split(' ')[0]
        except:
            pass
        try:
            employee.firstname = fio.split(' ')[1]
        except:
            pass
        try:
            employee.patronymic = fio.split(' ')[2]
        except:
            pass
        employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0015_auto_20180221_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250, unique=True, verbose_name='Табельный номер сотрудника в организации контрагента')),
                ('start', models.DateField(verbose_name='Дата начала работы в организации контрагента')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы в организации контрагента')),
            ],
            options={
                'verbose_name': 'История назначений агентств',
                'verbose_name_plural': 'История назначений агентств',
                'ordering': ['-start'],
            },
        ),
        migrations.AlterModelOptions(
            name='agencyemployee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='firstname',
            field=models.CharField(default='', max_length=250, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=8, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='patronymic',
            field=models.CharField(default='', max_length=250, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='surname',
            field=models.CharField(default='', max_length=250, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orghistory',
            name='agency_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.AgencyEmployee'),
        ),
        migrations.AddField(
            model_name='orghistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization'),
        ),
        migrations.RunPython(set_names),
        migrations.RemoveField(
            model_name='agencyemployee',
            name='name',
        ),
    ]
