# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0016_auto_20180226_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outsource.Agency', verbose_name='Агентство'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outsource.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='outsourcingshift',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
        ),
    ]
