# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def set_agency(apps, schema_editor):
    AgencyEmployee = apps.get_model("outsource", "AgencyEmployee")
    AgencyHistory = apps.get_model("outsource", "AgencyHistory")
    for employee in AgencyEmployee.objects.all():
        try:
            out_agency = AgencyHistory.objects.get(agency_employee=employee)
        except:
            out_agency = AgencyHistory.objects.all().first()
        employee.agency_id = out_agency.agency.id
        employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0017_auto_20180226_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemployee',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
            preserve_default=False,
        ),
        migrations.RunPython(set_agency),
    ]
