# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc

def set_dates(apps, schema_editor):
    AgencyEmployee = apps.get_model("outsource", "AgencyEmployee")
    AgencyHistory = apps.get_model("outsource", "AgencyHistory")
    for employee in AgencyEmployee.objects.all():
        out_agency = AgencyHistory.objects.get(agency_employee=employee)
        employee.receipt = out_agency.start
        employee.dismissal = out_agency.end
        employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0018_agencyemployee_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemployee',
            name='dismissal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='receipt',
            field=models.DateField(default=datetime.datetime(2018, 2, 26, 14, 16, 22, 485847, tzinfo=utc), verbose_name='Дата приема'),
            preserve_default=False,
        ),
        migrations.RunPython(set_dates),
    ]
