# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0019_auto_20180226_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='дата-время создания')),
                ('kind', models.CharField(choices=[('receipt_req', 'Receipt request'), ('receipt_res', 'Receipt request result')], max_length=16, verbose_name='вид события')),
                ('need_to_send', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency')),
                ('agency_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.AgencyEmployee')),
            ],
            options={
                'verbose_name': 'Событие сотрудника',
                'verbose_name_plural': 'Cобытия сотрудника',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Headquater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название клиента')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Уникальный код клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Справочник клиентов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater'),
        ),
    ]
