# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0020_auto_20180227_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EmployeeEvent',
        ),
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('store', 'Store'), ('city', 'City')], default='store', max_length=8, verbose_name='Тип'),
        ),
    ]
