# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_def_headquater(apps, schema_editor):
    Headquater = apps.get_model("outsource", "Headquater")
    def_headquater = Headquater(name="Headquater", code="head_1")
    def_headquater.save()

class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0021_auto_20180228_1044'),
    ]

    operations = [
        migrations.RunPython(create_def_headquater),
        migrations.AddField(
            model_name='organization',
            name='headquater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
