# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0022_organization_headquater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyemployee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=250, verbose_name='Отчество'),
        ),
    ]
