# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0024_auto_20180228_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Агентство', 'verbose_name_plural': 'Агентства'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name'], 'verbose_name': 'Функция', 'verbose_name_plural': 'Функции'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='outsourcingrequest',
            options={'ordering': ['-id'], 'verbose_name': 'Запрос сотрудников у контрагента', 'verbose_name_plural': 'Запросы'},
        ),
    ]
