# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outsource', '0025_auto_20180228_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
