# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outsource', '0026_employeeevent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now=True, verbose_name='Дата/время создания')),
                ('kind', models.CharField(choices=[('recruitment', 'Recruitment'), ('dismissal', 'Dismissal'), ('change', 'Change')], max_length=16, verbose_name='Тип события')),
                ('number', models.CharField(max_length=250, null=True, verbose_name='Табельный номер сотрудника агентства')),
                ('recruitment_date', models.DateField(null=True, verbose_name='Дата приема сотрудника')),
                ('dismissal_date', models.DateField(null=True, verbose_name='Дата увольнения сотрудника')),
                ('dismissal_reason', models.CharField(blank=True, max_length=1000, verbose_name='Причина увольнения')),
                ('reject_reason', models.CharField(blank=True, max_length=1000, verbose_name='Причина отказа')),
                ('agency_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.AgencyEmployee')),
            ],
            options={
                'verbose_name': 'Внешнее событие сотрудника',
                'verbose_name_plural': 'Внешние события сотрудника',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='employeeevent',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='dismissal_date',
            field=models.DateField(null=True, verbose_name='Дата увольнения сотрудника'),
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='dismissal_reason',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Причина увольнения'),
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='dt_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата/время создания'),
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID'),
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization'),
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='recruitment_date',
            field=models.DateField(null=True, verbose_name='Дата приема сотрудника'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='kind',
            field=models.CharField(choices=[('receipt_req', 'Receipt request'), ('receipt_res', 'Receipt request result')], max_length=16, verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='employeehisory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.EmployeeEvent'),
        ),
        migrations.AddField(
            model_name='employeehisory',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater'),
        ),
        migrations.AddField(
            model_name='employeehisory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization'),
        ),
        migrations.AddField(
            model_name='employeehisory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
