# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0028_auto_20180301_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevent',
            name='kind',
            field=models.CharField(choices=[('recruitment', 'Recruitment'), ('dismissal', 'Dismissal'), ('change', 'Change')], max_length=16, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='kind',
            field=models.CharField(choices=[('accept_recruitment', 'Accept'), ('reject_recruitment', 'Reject'), ('dismissal', 'Dismissal')], max_length=20, verbose_name='Тип события'),
        ),
    ]
