# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0029_auto_20180301_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevent',
            name='dismissal_reason',
            field=models.CharField(max_length=1000, null=True, verbose_name='Причина увольнения'),
        ),
    ]
