# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0030_auto_20180301_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orghistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Организация'),
        ),
    ]
