# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0031_auto_20180301_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
