# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0032_auto_20180302_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headquater',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='headquater',
            name='code',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='headquater',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
