# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0033_auto_20180302_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourcingrequest',
            name='state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('ready', 'Ready')], default='accepted', max_length=8, verbose_name='Статус обработки'),
        ),
    ]
