# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0035_auto_20180302_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyemployee',
            name='number',
            field=models.CharField(max_length=250, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='По'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='start',
            field=models.DateField(verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='orghistory',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='orghistory',
            name='number',
            field=models.CharField(max_length=250, unique=True, verbose_name='ТН в организации'),
        ),
        migrations.AlterField(
            model_name='orghistory',
            name='start',
            field=models.DateField(verbose_name='Дата приема'),
        ),
    ]
