# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0036_auto_20180305_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outsource.Organization', verbose_name='Город'),
        ),
    ]
