# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0037_auto_20180305_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orghistory',
            options={'ordering': ['-start'], 'verbose_name': 'История назначений организаций', 'verbose_name_plural': 'История назначений организаций'},
        ),
    ]
