# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0038_auto_20180305_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.EmployeeEvent'),
        ),
    ]
