# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0039_auto_20180305_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeevent',
            options={'ordering': ['-id'], 'verbose_name': 'Событие сотрудника', 'verbose_name_plural': 'Внутренние кадровые мероприятия'},
        ),
    ]
