# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def set_agency(apps, schema_editor):
    EmployeeHistory = apps.get_model("outsource", "EmployeeHistory")
    for history in EmployeeHistory.objects.all():
        history.agency_id = history.agency_employee.agency.id
        history.save()

class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0040_auto_20180306_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevent',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
        ),
        migrations.RunPython(set_agency),
    ]
