# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0041_auto_20180306_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeevent',
            options={'ordering': ['-id'], 'verbose_name': 'Кадровое мероприятие — Внутреннее', 'verbose_name_plural': 'Кадровые мероприятия — Внутренние'},
        ),
        migrations.AlterModelOptions(
            name='employeehistory',
            options={'ordering': ['-id'], 'verbose_name': 'Кадровое мероприятие — Внешнее', 'verbose_name_plural': 'Кадровые мероприятия — Внешние'},
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='agency_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.AgencyEmployee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='dt_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='kind',
            field=models.CharField(choices=[('recruitment', 'Recruitment'), ('dismissal', 'Dismissal'), ('change', 'Change')], max_length=16, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
