# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0042_auto_20180306_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeevent',
            name='need_to_send',
        ),
    ]
