# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0043_remove_employeeevent_need_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevent',
            name='ext_number',
            field=models.CharField(max_length=250, null=True, verbose_name='ТН в организации'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='dismissal_reason',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Причина увольнения'),
            preserve_default=False,
        ),
    ]
