# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0045_auto_20180306_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevent',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='Включен в черный список'),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='ext_number',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='ТН в организации'),
            preserve_default=False,
        ),
    ]
