# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0046_auto_20180306_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeehistory',
            name='number',
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='ext_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='ТН в организации'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='agency_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.AgencyEmployee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='Включен в черный список'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='dt_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.EmployeeEvent', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='kind',
            field=models.CharField(choices=[('accept_recruitment', 'Accept'), ('reject_recruitment', 'Reject'), ('dismissal', 'Dismissal')], max_length=20, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
