# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0050_auto_20180306_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='headquater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
        ),
    ]
