# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0051_accessprofile_headquater'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghistory',
            name='headquater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outsourcingrequest',
            name='headquater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outsourcingshift',
            name='headquater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
