# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_outsourcing_request_headquater(apps, schema_editor):
    OutsourcingRequest = apps.get_model("outsource", "OutsourcingRequest")
    OutsourcingShift = apps.get_model("outsource", "OutsourcingShift")
    for out_req in OutsourcingRequest.objects.all():
        out_req.headquater_id = out_req.organization.headquater_id
        out_req.save()
        OutsourcingShift.objects.filter(request=out_req).update(headquater_id=out_req.headquater_id)

def set_orghistory_headquater(apps, schema_editor):
    OrgHistory = apps.get_model("outsource", "OrgHistory")
    for org_hist in OrgHistory.objects.all():
        org_hist.headquater_id = org_hist.organization.headquater_id
        org_hist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0052_auto_20180313_1849'),
    ]

    operations = [
        migrations.RunPython(set_outsourcing_request_headquater),
        migrations.RunPython(set_orghistory_headquater),
    ]
