# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def set_orglink_headquater(apps, schema_editor):
    OrgLink = apps.get_model("outsource", "OrgLink")
    for org_link in OrgLink.objects.all():
        if org_link.organization:
            org_link.headquater_id = org_link.organization.headquater_id
            org_link.save()

class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0055_auto_20180321_1435'),
    ]

    operations = [
        migrations.RunPython(set_orglink_headquater),
    ]
