# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0056_orglink_set_headquater'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevent',
            name='answer_received',
            field=models.BooleanField(default=False, verbose_name='Получен ответ на событие'),
        ),
    ]
