# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0057_employeeevent_answer_received'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orghistory',
            unique_together=set([('number', 'organization', 'start')]),
        ),
    ]
