# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0058_auto_20180405_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquater',
            name='accept_req_template',
            field=models.SlugField(blank=True, verbose_name='Шаблон уведомления о подтверждении заявки'),
        ),
        migrations.AddField(
            model_name='headquater',
            name='delete_shift_template',
            field=models.SlugField(blank=True, verbose_name='Шаблон уведомления об отказе от смены'),
        ),
        migrations.AddField(
            model_name='headquater',
            name='wait_req_template',
            field=models.SlugField(blank=True, verbose_name='Шаблон уведомления о новой заявке'),
        ),
    ]
