# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0062_outsourcingrequest_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outsourcingrequest',
            old_name='comment',
            new_name='comments',
        ),
    ]
