# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import apps.outsource.models
import apps.claims.models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0063_auto_20180522_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Название файла')),
                ('attachment', models.FileField(upload_to=apps.claims.models.user_directory_path, verbose_name='Путь')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Тип претензии',
                'verbose_name_plural': 'Типы претензий',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент')], max_length=8, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО пользователя')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст претензии')),
                ('number', models.CharField(max_length=250, verbose_name='Номер')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('dt_closed', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство')),
            ],
            options={
                'verbose_name': 'Претензия',
                'verbose_name_plural': 'Претензии',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('code', models.CharField(max_length=250, unique=True, verbose_name='Код')),
                ('sort_key', models.IntegerField(verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Тип претензии',
                'verbose_name_plural': 'Типы пренезий',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='headquater',
            name='prefix',
            field=models.CharField(blank=True, max_length=255, verbose_name='Префикс'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='claim_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.ClaimType', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='claimmessage',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.ClaimRequest', verbose_name='Претензия'),
        ),
        migrations.AddField(
            model_name='claimattach',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.ClaimRequest', verbose_name='Претензия'),
        ),
    ]
