# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0064_auto_20180523_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimattach',
            options={'ordering': ['-id'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='claimtype',
            options={'ordering': ['-id'], 'verbose_name': 'Тип претензии', 'verbose_name_plural': 'Типы претезий'},
        ),
    ]
