# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0066_claimattach_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
    ]
