# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0067_auto_20180524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimattach',
            name='claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.ClaimRequest', verbose_name='Претензия'),
        ),
    ]
