# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0070_auto_20180528_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='dt_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлена'),
        ),
    ]
