# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0071_claimrequest_dt_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='dt_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 31, 11, 52, 2, 359520, tzinfo=utc), verbose_name='Обновлена'),
            preserve_default=False,
        ),
    ]
