# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0072_auto_20180531_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО пользователя'),
        ),
    ]
