# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import apps.outsource.models
import apps.claims.models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0073_claimrequest_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Название файла')),
                ('size', models.IntegerField(null=True, verbose_name='Размер')),
                ('mime', models.CharField(max_length=255, null=True, verbose_name='MIME-тип')),
                ('attachment', models.FileField(upload_to=apps.claims.models.user_directory_path, verbose_name='Путь')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.TextField(verbose_name='Описание')),
                ('headquater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-id'],
            },
        ),
    ]
