# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0074_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('max_file_size', 'Максимальный размер загружаемых файлов, Мб.'), ('wait_req_template', 'Шаблон уведомления о новой заявке'), ('accept_req_template', 'Шаблон уведомления о подтверждении заявки'), ('delete_shift_template', 'Шаблон уведомления об отказе от смены'), ('create_claim_template', 'Шаблон уведомления о новой претензии'), ('close_claim_template', 'Шаблон уведомления о закрытии претензии'), ('msg_agency_template', 'Шаблон уведомления о сообщении от агентства'), ('msg_headquarter_template', 'Шаблон уведомления о сообщении от клиента')], max_length=1024, verbose_name='Ключ')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('headquater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
