# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0075_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(choices=[('max_file_size', 'Максимальный размер загружаемых файлов, Мб.'), ('wait_req_template', 'Шаблон уведомления о новой заявке'), ('accept_req_template', 'Шаблон уведомления о подтверждении заявки'), ('delete_shift_template', 'Шаблон уведомления об отказе от смены'), ('create_claim_template', 'Шаблон уведомления о новой претензии'), ('close_claim_template', 'Шаблон уведомления о закрытии претензии'), ('msg_agency_template', 'Шаблон уведомления о сообщении от агентства'), ('msg_headquarter_template', 'Шаблон уведомления о сообщении от клиента')], max_length=100, verbose_name='Ключ'),
        ),
    ]
