# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0076_auto_20180608_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Значение'),
        ),
    ]
