# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0078_migrate_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headquater',
            name='accept_req_template',
        ),
        migrations.RemoveField(
            model_name='headquater',
            name='delete_shift_template',
        ),
        migrations.RemoveField(
            model_name='headquater',
            name='wait_req_template',
        ),
    ]
