# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0079_auto_20180608_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(choices=[('max_file_size', 'Максимальный размер загружаемых файлов, Мб.'), ('wait_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Новая'), ('accept_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Подтверждена'), ('delete_shift_template', 'Шаблон уведомления - Заявка на аутсорсинг - Отказ от смены'), ('create_claim_template', 'Шаблон уведомления - Претензия - Новая'), ('close_claim_template', 'Шаблон уведомления - Претензия - Закрыта'), ('msg_agency_template', 'Шаблон уведомления - Претензия - Сообщение от агентства'), ('msg_headquarter_template', 'Шаблон уведомления - Претензия - Сообщение от клиента')], max_length=100, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='outsourcingrequest',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='GUID'),
        ),
    ]
