# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0082_auto_20180628_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Код')),
                ('sort_key', models.PositiveIntegerField(default=1, verbose_name='индекс сортировки')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClaimHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='обновлено')),
                ('party', models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент')], max_length=8, verbose_name='Сторона')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО пользователя')),
                ('text', models.TextField(verbose_name='Текст претензии')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.ClaimRequest', verbose_name='Претензия')),
            ],
            options={
                'verbose_name': 'История согласований',
                'verbose_name_plural': 'Истории согласований',
                'ordering': ['-dt_created'],
            },
        ),
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Код')),
                ('sort_key', models.PositiveIntegerField(default=1, verbose_name='индекс сортировки')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='claimhistory',
            name='state_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outsource.ClaimStatus', verbose_name='предыдущее состояние'),
        ),
        migrations.AddField(
            model_name='claimhistory',
            name='state_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outsource.ClaimStatus', verbose_name='текущее состояние'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.ClaimStatus', verbose_name='Статус'),
        ),
    ]
