# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0083_auto_20180628_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimaction',
            name='need_comment',
            field=models.BooleanField(default=False, verbose_name='требуется комментарий'),
        ),
    ]
