# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0084_claimaction_need_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimaction',
            options={'ordering': ['name'], 'verbose_name': 'Претензия: Действие', 'verbose_name_plural': 'Претензия: Действия'},
        ),
        migrations.AlterModelOptions(
            name='claimstatus',
            options={'ordering': ['name'], 'verbose_name': 'Претензия: Статус', 'verbose_name_plural': 'Претензия: Статусы'},
        ),
        migrations.AlterModelOptions(
            name='claimtype',
            options={'ordering': ['-id'], 'verbose_name': 'Претензия: Тип', 'verbose_name_plural': 'Претензия: Типы'},
        ),
    ]
