# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0086_claim_types_actions_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='dt_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменен статус'),
        ),
    ]
