# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0087_auto_20180629_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(choices=[('max_file_size', 'Максимальный размер загружаемых файлов, Мб.'), ('wait_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Новая'), ('accept_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Подтверждена'), ('reject_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Отклонена'), ('delete_shift_template', 'Шаблон уведомления - Заявка на аутсорсинг - Отказ от смены'), ('create_claim_template', 'Шаблон уведомления - Претензия - Новая'), ('close_claim_template', 'Шаблон уведомления - Претензия - Закрыта'), ('accept_claim_template', 'Шаблон уведомления - Претензия - Принята'), ('reject_claim_template', 'Шаблон уведомления - Претензия - Отклонена'), ('msg_agency_template', 'Шаблон уведомления - Претензия - Сообщение от агентства'), ('msg_headquarter_template', 'Шаблон уведомления - Претензия - Сообщение от клиента')], max_length=100, verbose_name='Ключ'),
        ),
    ]
