# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0088_auto_20180629_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequest',
            old_name='dt_closed',
            new_name='dt_status_changed',
        ),
    ]
