# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0089_auto_20180629_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimhistory',
            name='text',
        ),
        migrations.AddField(
            model_name='claimhistory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментаний'),
        ),
    ]
