# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-02 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0090_auto_20180702_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='dt_status_changed',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Изменен статус'),
        ),
    ]
