# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-17 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0092_auto_20180717_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name'], 'verbose_name': 'Функция', 'verbose_name_plural': 'Справочник функций'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Орг. структура', 'verbose_name_plural': 'Орг. структура'},
        ),
    ]
