# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0093_auto_20180817_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquater',
            name='party',
            field=models.CharField(choices=[('client', 'Клиент'), ('agency', 'Агентство')], default='client', max_length=8, verbose_name='Тип'),
        ),
    ]
