# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0094_headquater_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='headquater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Подразделение'),
        ),
    ]
