# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0096_agency_to headquater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headquater',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='headquater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('store', 'Store'), ('city', 'City'), ('head', 'Head')], default='store', max_length=8, verbose_name='Тип'),
        ),
    ]
