# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0097_auto_20180822_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Агентства - Орг. структура', 'verbose_name_plural': 'Агентства - Орг. структура'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Клиенты - Орг. структура', 'verbose_name_plural': 'Клиенты - Орг. структура'},
        ),
    ]
