# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0099_auto_20180822_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('store', 'Store'), ('city', 'City'), ('head', 'Head')], default='store', max_length=8, verbose_name='Тип'),
        ),
    ]
