# Generated by Django 2.0.5 on 2018-09-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0102_organization_last_external_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_type', models.CharField(choices=[('fix', 'Fix'), ('app', 'App')], default='fix', max_length=8, verbose_name='Тип')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Квота',
                'verbose_name_plural': 'Квоты',
            },
        ),
        migrations.CreateModel(
            name='QuotaVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Объем квот',
                'verbose_name_plural': 'Объем квот',
            },
        ),
        migrations.CreateModel(
            name='StoreArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'КБГ',
                'verbose_name_plural': 'КБГ',
            },
        ),
        migrations.AddField(
            model_name='quotavolume',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.StoreArea', verbose_name='КБГ'),
        ),
        migrations.AddField(
            model_name='quotavolume',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='quota',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.StoreArea', verbose_name='КБГ'),
        ),
        migrations.AddField(
            model_name='quota',
            name='promo',
            field=models.ForeignKey(limit_choices_to={'party': 'promo'}, on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='quota',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Магазин'),
        ),
    ]
