# Generated by Django 2.0.5 on 2018-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0103_auto_20180927_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='outsource.Job', verbose_name='Функции'),
        ),
    ]
