# Generated by Django 2.0.5 on 2018-10-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0104_auto_20180928_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together={('store', 'area', 'promo')},
        ),
    ]
