"""
Copyright 2018 ООО «Верме»

Миграция базы данных приложения outsource
"""

# Generated by Django 2.0.5 on 2018-10-11 12:05

from django.db import migrations, models
import django.db.models.deletion


def set_aheadquarter_based_on_agency(apps, schema_editor):
    OrgLink = apps.get_model('outsource', 'OrgLink')
    for orglink in OrgLink.objects.all().iterator():
        orglink.aheadquarter = orglink.agency.headquater
        orglink.save()


class Migration(migrations.Migration):
    dependencies = [
        ('outsource', '0107_auto_20181011_1448'),
    ]

    operations = [
        # First, make new field nullable
        migrations.AddField(
            model_name='orglink',
            name='aheadquarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='outsource_aheadquarters_related', to='outsource.Headquater',
                                    verbose_name='Компания-промоутер'),
            preserve_default=False,
        ),
        # Second, populate new field with values based on another field
        migrations.RunPython(set_aheadquarter_based_on_agency),
        # Lastly, make fill non-nullable
        migrations.AlterField(
            model_name='orglink',
            name='aheadquarter',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='outsource_aheadquarters_related', to='outsource.Headquater',
                                    verbose_name='Компания-промоутер')
        ),

        migrations.AlterField(
            model_name='orglink',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='outsource_headquarters_related', to='outsource.Headquater',
                                    verbose_name='Клиент'),
        ),
    ]
