# Generated by Django 2.0.5 on 2018-10-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0108_auto_20181011_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orglink',
            options={'ordering': ['-id'], 'verbose_name': 'Связь между агентствами и организациями', 'verbose_name_plural': 'Связи между агентствами и организациями'},
        ),
        migrations.AlterField(
            model_name='orglink',
            name='aheadquarter',
            field=models.ForeignKey(limit_choices_to={'party__in': ['agency', 'promo']}, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_aheadquarters_related', to='outsource.Headquater', verbose_name='Компания-промоутер'),
        ),
        migrations.AlterField(
            model_name='orglink',
            name='headquater',
            field=models.ForeignKey(limit_choices_to={'party': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_headquarters_related', to='outsource.Headquater', verbose_name='Клиент'),
        ),
    ]
