# Generated by Django 2.0.5 on 2018-10-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0109_auto_20181011_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storearea',
            options={'verbose_name': 'Зона магазина ', 'verbose_name_plural': 'Зоны магазина'},
        ),
        migrations.AlterField(
            model_name='quota',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.StoreArea', verbose_name='Зона магазина'),
        ),
        migrations.AlterField(
            model_name='quotavolume',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.StoreArea', verbose_name='Зона магазина'),
        ),
    ]
