# Generated by Django 2.0.5 on 2018-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0110_auto_20181015_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Значение'),
        ),
    ]
