# Generated by Django 2.0.5 on 2018-10-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0112_auto_20181026_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='headquarter',
            field=models.ForeignKey(default=1, limit_choices_to={'party': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_quotas_headquarters_related', to='outsource.Headquater', verbose_name='Компания клиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quota',
            name='promo',
            field=models.ForeignKey(limit_choices_to={'party': 'promo'}, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_quotas_promos_related', to='outsource.Headquater', verbose_name='Компания'),
        ),
    ]
