# Generated by Django 2.0.5 on 2018-10-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0113_set_quotas_headquater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orglink',
            name='aheadquarter',
            field=models.ForeignKey(limit_choices_to={'party__in': ['agency', 'promo']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_aheadquarters_related', to='outsource.Headquater', verbose_name='Компания-промоутер'),
        ),
    ]
