# Generated by Django 2.0.5 on 2018-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0114_auto_20181031_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(choices=[('max_file_size', 'Максимальный размер загружаемых файлов, Мб.'), ('wait_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Новая'), ('accept_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Подтверждена'), ('reject_req_template', 'Шаблон уведомления - Заявка на аутсорсинг - Отклонена'), ('delete_shift_template', 'Шаблон уведомления - Заявка на аутсорсинг - Отказ от смены'), ('create_claim_template', 'Шаблон уведомления - Претензия - Новая'), ('close_claim_template', 'Шаблон уведомления - Претензия - Закрыта'), ('accept_claim_template', 'Шаблон уведомления - Претензия - Принята'), ('reject_claim_template', 'Шаблон уведомления - Претензия - Отклонена'), ('msg_agency_template', 'Шаблон уведомления - Претензия - Сообщение от агентства'), ('msg_headquarter_template', 'Шаблон уведомления - Претензия - Сообщение от клиента'), ('max_shifts_per_day', 'Максимальное количество смен сотрудника в день')], max_length=100, verbose_name='Ключ'),
        ),
    ]
