# Generated by Django 2.0.5 on 2018-11-16 08:41

import apps.lib.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0115_auto_20181115_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=apps.lib.forms.ConfigChoiceField(max_length=24, verbose_name='ключ'),
        ),
    ]
