# Generated by Django 2.0.5 on 2019-01-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0116_auto_20181116_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquater',
            name='party',
            field=models.CharField(choices=[('client', 'Клиент'), ('agency', 'Агентство'), ('promo', 'Промоутер'), ('broker', 'Кредитный брокер')], default='client', max_length=8, verbose_name='Тип'),
        ),
    ]
