# Generated by Django 2.0.5 on 2019-01-11 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0117_auto_20190110_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='По'),
        ),
        migrations.AddField(
            model_name='quota',
            name='start',
            field=models.DateField(default=datetime.date(2019, 1, 1), verbose_name='С'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quota',
            name='value_ext',
            field=models.PositiveIntegerField(default=0, verbose_name='Согласованные квоты'),
        ),
        migrations.AddField(
            model_name='quotavolume',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='По'),
        ),
        migrations.AddField(
            model_name='quotavolume',
            name='kind',
            field=models.CharField(choices=[('max_by_square', 'max_by_square')], default='max_by_square', max_length=16, verbose_name='Вид'),
        ),
        migrations.AddField(
            model_name='quotavolume',
            name='start',
            field=models.DateField(default=datetime.date(2019, 1, 1), verbose_name='С'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quota',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Стендовые квоты'),
        ),
    ]
