# Generated by Django 2.0.5 on 2019-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0118_auto_20190111_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquater',
            name='short',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сокращенное название'),
        ),
    ]
