# Generated by Django 2.0.5 on 2019-02-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0120_quota_values_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='promo',
            field=models.ForeignKey(limit_choices_to={'party__in': ['promo', 'broker']}, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_quotas_promos_related', to='outsource.Headquater', verbose_name='Компания'),
        ),
    ]
