# Generated by Django 2.0.5 on 2019-02-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0121_auto_20190201_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together={('store', 'area', 'promo', 'start')},
        ),
    ]
