# Generated by Django 2.0.5 on 2019-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0122_auto_20190205_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='end',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='По'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='start',
            field=models.DateField(db_index=True, verbose_name='С'),
        ),
    ]
