# Generated by Django 2.0.5 on 2019-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0123_auto_20190206_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='Стендовые квоты'),
        ),
        migrations.AlterField(
            model_name='quotavolume',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение'),
        ),
    ]
