# Generated by Django 2.0.5 on 2019-03-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0125_fix_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Вышестоящая орг. единица'),
        ),
    ]
