# Generated by Django 2.0.5 on 2019-03-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0126_auto_20190304_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquater',
            name='party',
            field=models.CharField(choices=[('client', 'Клиент'), ('agency', 'Аутсорсинг'), ('promo', 'Вендоры'), ('broker', 'Кредитный брокер')], default='client', max_length=8, verbose_name='Тип'),
        ),
    ]
