# Generated by Django 2.0.5 on 2019-04-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0128_auto_20190312_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts_count', models.PositiveIntegerField(default=0, verbose_name='Количество смен')),
                ('open_shifts_count', models.PositiveIntegerField(default=0, verbose_name='Количество открытых смен')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Quota', verbose_name='Квота')),
            ],
            options={
                'verbose_name': 'Информация по квоте',
                'verbose_name_plural': 'Информация по квоте',
            },
        ),
    ]
