# Generated by Django 2.0.5 on 2019-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0131_quotainfo_dt_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotainfo',
            name='quota_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер квоты'),
        ),
    ]
