# Generated by Django 2.0.5 on 2019-04-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0132_quotainfo_quota_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orglink',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsource_agency_related', to='outsource.Agency', verbose_name='Агентство'),
        ),
        migrations.AlterField(
            model_name='orglink',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_organizations_related', to='outsource.Organization', verbose_name='Организация'),
        ),
    ]
