# Generated by Django 2.0.5 on 2019-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0133_auto_20190425_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquater',
            name='is_transition',
            field=models.BooleanField(default=False, verbose_name='Разрешен перевод сотрудников внутри компании'),
        ),
    ]
