# Generated by Django 2.0.5 on 2019-05-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0134_headquater_is_transition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headquater',
            name='is_transition',
        ),
    ]
