# Generated by Django 2.0.5 on 2019-06-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_agencymanager'),
        ('outsource', '0135_remove_headquater_is_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='actual_address',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, verbose_name='Доп. информация'),
        ),
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='EMail'),
        ),
        migrations.AddField(
            model_name='agency',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='agency',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.AgencyManager', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='agency',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сайт'),
        ),
    ]
