# Generated by Django 2.0.5 on 2019-06-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0136_auto_20190610_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='manager',
        ),
    ]
