# Generated by Django 2.0.5 on 2018-12-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Код')),
                ('icon', models.CharField(default='warning', help_text='название со страницы https://fortawesome.github.io/Font-Awesome/icons/', max_length=64, verbose_name='Иконка')),
                ('party', models.CharField(choices=[('client', 'Клиент'), ('agency', 'Агентство'), ('promo', 'Промоутер')], default='client', max_length=8, verbose_name='Статус регистрации')),
                ('show_in_agency_filter', models.BooleanField(default=False, verbose_name='Отображать в фильтре агентства')),
                ('show_in_client_filter', models.BooleanField(default=False, verbose_name='Отображать в фильтре клиента')),
                ('show_in_schedule', models.BooleanField(default=False, verbose_name='Отображать в интерфейсе планирования')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ViolationRuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('severity', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=8, verbose_name='Важность')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('message', models.CharField(max_length=1000, verbose_name='Сообщение')),
                ('show_in_agency_filter', models.BooleanField(default=False, verbose_name='Отображать в фильтре агентства')),
                ('show_in_client_filter', models.BooleanField(default=False, verbose_name='Отображать в фильтре клиента')),
                ('show_in_schedule', models.BooleanField(default=False, verbose_name='Отображать в интерфейсе планирования')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.ViolationRule', verbose_name='Нарушение')),
            ],
            options={
                'verbose_name': 'Уровень нарушения',
                'verbose_name_plural': 'Уровни нарушений',
                'ordering': ['name'],
            },
        ),
    ]
