# Generated by Django 2.0.5 on 2018-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_auto_20181228_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationrule',
            name='icon',
            field=models.CharField(default='exclamation-triangle', help_text='название со страницы https://fortawesome.github.io/Font-Awesome/icons/', max_length=64, verbose_name='Иконка'),
        ),
    ]
