# Generated by Django 2.0.5 on 2019-01-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0004_auto_20190110_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationrule',
            name='code',
            field=models.CharField(choices=[('medical', 'Наличие мед. книжки'), ('blacklist', 'Включен в черный список'), ('dismissed_by_agency', 'Уволен агентством'), ('dismissed_by_client', 'Уволен клиентом'), ('wait_register', 'Ожидает регистрации у клиента')], default='medical', max_length=32, unique=True, verbose_name='Код'),
        ),
    ]
