# Generated by Django 2.0.5 on 2019-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0005_auto_20190117_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationruleitem',
            name='value',
        ),
        migrations.AddField(
            model_name='violationruleitem',
            name='value_from',
            field=models.IntegerField(default=0, verbose_name='Значение от'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violationruleitem',
            name='value_to',
            field=models.IntegerField(default=0, verbose_name='Значение до'),
            preserve_default=False,
        ),
    ]
