# Generated by Django 2.0.5 on 2019-03-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0006_auto_20190122_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationrule',
            name='party',
            field=models.CharField(choices=[('client', 'Клиент'), ('agency', 'Аутсорсинг'), ('promo', 'Вендоры'), ('broker', 'Кредитный брокер')], default='client', max_length=8, verbose_name='Сторона'),
        ),
    ]
