# Generated by Django 2.0.5 on 2019-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0019_page_date_changer_mode'),
        ('violations', '0007_auto_20190312_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationrule',
            name='party',
        ),
        migrations.RemoveField(
            model_name='violationrule',
            name='show_in_agency_filter',
        ),
        migrations.RemoveField(
            model_name='violationrule',
            name='show_in_client_filter',
        ),
        migrations.RemoveField(
            model_name='violationrule',
            name='show_in_schedule',
        ),
        migrations.RemoveField(
            model_name='violationruleitem',
            name='show_in_agency_filter',
        ),
        migrations.RemoveField(
            model_name='violationruleitem',
            name='show_in_client_filter',
        ),
        migrations.RemoveField(
            model_name='violationruleitem',
            name='show_in_schedule',
        ),
        migrations.AddField(
            model_name='violationrule',
            name='pages',
            field=models.ManyToManyField(blank=True, to='permission.Page', verbose_name='страницы'),
        ),
    ]
