# Generated by Django 2.0.5 on 2019-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0009_auto_20190410_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationrule',
            name='code',
            field=models.CharField(choices=[('medical', 'Наличие мед. книжки'), ('blacklist', 'Включен в черный список'), ('dismissed_by_agency', 'Уволен агентством'), ('dismissed_by_client', 'Уволен клиентом'), ('wait_register', 'Ожидает регистрации у клиента'), ('quota_no_shifts', 'Квоты без смен'), ('quota_open_shifts', 'Квоты с открытыми сменами'), ('medical_no_files', 'Наличие файлов мед. книжки'), ('employee_no_shifts', 'Не назначен на смену')], default='medical', max_length=32, unique=True, verbose_name='Код'),
        ),
    ]
