# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.CharField(max_length=128, verbose_name='описание')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='уникальный код')),
                ('endpoint', models.CharField(max_length=128, verbose_name='адрес web-службы')),
                ('action', models.CharField(max_length=128, verbose_name='имя web-метода')),
                ('oneway', models.BooleanField(help_text='0 - запрос-ответ, 1 - только запрос', verbose_name='способ взаимодействия')),
                ('timeout', models.IntegerField(verbose_name='время ожидания ответа, сек.')),
                ('protocol', models.CharField(choices=[('JSON', 'JSON')], default='JSON', max_length=4, verbose_name='Протокол')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль')),
                ('is_public', models.BooleanField(default=False, verbose_name='Общедоступный сервис')),
                ('method', models.CharField(choices=[('Sync', 'Sync'), ('Async', 'Async')], default='Sync', max_length=5, verbose_name='Режим работы')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Внешний сервис',
                'verbose_name_plural': 'Внешние сервисы',
            },
        ),
    ]
