# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 13:04
from __future__ import unicode_literals

import apps.claims.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outsource', '0092_auto_20180717_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Код')),
                ('sort_key', models.PositiveIntegerField(default=1, verbose_name='индекс сортировки')),
                ('need_comment', models.BooleanField(default=False, verbose_name='требуется комментарий')),
            ],
            options={
                'verbose_name': 'Претензия: Действие',
                'verbose_name_plural': 'Претензия: Действия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Название файла')),
                ('size', models.IntegerField(null=True, verbose_name='Размер')),
                ('mime', models.CharField(max_length=255, null=True, verbose_name='MIME-тип')),
                ('attachment', models.FileField(upload_to=apps.claims.models.user_directory_path, verbose_name='Путь')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='обновлено')),
                ('party', models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент')], max_length=8, verbose_name='Сторона')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО пользователя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментаний')),
            ],
            options={
                'verbose_name': 'История согласований',
                'verbose_name_plural': 'Истории согласований',
                'ordering': ['-dt_created'],
            },
        ),
        migrations.CreateModel(
            name='ClaimMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент')], max_length=8, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО пользователя')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст претензии')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО пользователя')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('dt_updated', models.DateTimeField(auto_now_add=True, verbose_name='Обновлена')),
                ('dt_status_changed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Изменен статус')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail адрес')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство')),
            ],
            options={
                'verbose_name': 'Претензия',
                'verbose_name_plural': 'Претензии',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('code', models.CharField(max_length=1000, unique=True, verbose_name='Код')),
                ('sort_key', models.PositiveIntegerField(default=1, verbose_name='индекс сортировки')),
            ],
            options={
                'verbose_name': 'Претензия: Статус',
                'verbose_name_plural': 'Претензия: Статусы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('code', models.CharField(max_length=250, unique=True, verbose_name='Код')),
                ('sort_key', models.IntegerField(verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Претензия: Тип',
                'verbose_name_plural': 'Претензия: Типы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Название файла')),
                ('size', models.IntegerField(null=True, verbose_name='Размер')),
                ('mime', models.CharField(max_length=255, null=True, verbose_name='MIME-тип')),
                ('attachment', models.FileField(upload_to=apps.claims.models.user_directory_path, verbose_name='Путь')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.TextField(verbose_name='Описание')),
                ('headquater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='claim_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.ClaimType', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='headquater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Headquater', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outsource.Organization', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='claims.ClaimStatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='claimmessage',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='claims.ClaimRequest', verbose_name='Претензия'),
        ),
        migrations.AddField(
            model_name='claimhistory',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.ClaimRequest', verbose_name='Претензия'),
        ),
        migrations.AddField(
            model_name='claimhistory',
            name='state_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='claims.ClaimStatus', verbose_name='предыдущее состояние'),
        ),
        migrations.AddField(
            model_name='claimhistory',
            name='state_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='claims.ClaimStatus', verbose_name='текущее состояние'),
        ),
        migrations.AddField(
            model_name='claimattach',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='claims.ClaimRequest', verbose_name='Претензия'),
        ),
        migrations.AddField(
            model_name='claimattach',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='claims.ClaimMessage', verbose_name='Сообщение'),
        ),
    ]
