# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claimaction',
            table='outsource_claimaction',
        ),
        migrations.AlterModelTable(
            name='claimattach',
            table='outsource_claimattach',
        ),
        migrations.AlterModelTable(
            name='claimhistory',
            table='outsource_claimhistory',
        ),
        migrations.AlterModelTable(
            name='claimmessage',
            table='outsource_claimmessage',
        ),
        migrations.AlterModelTable(
            name='claimrequest',
            table='outsource_claimrequest',
        ),
        migrations.AlterModelTable(
            name='claimstatus',
            table='outsource_claimstatus',
        ),
        migrations.AlterModelTable(
            name='claimtype',
            table='outsource_claimtype',
        ),
        migrations.AlterModelTable(
            name='document',
            table='outsource_document',
        ),
    ]
