# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_auto_20180717_1605'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claimaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='claimattach',
            table=None,
        ),
        migrations.AlterModelTable(
            name='claimhistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='claimmessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='claimrequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='claimstatus',
            table=None,
        ),
        migrations.AlterModelTable(
            name='claimtype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
