# Generated by Django 2.0.5 on 2018-09-25 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_auto_20180817_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID'),
        ),
    ]
