# Generated by Django 2.0.5 on 2018-10-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_auto_20180925_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='number',
        ),
    ]
