# Generated by Django 2.0.5 on 2019-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_remove_claimrequest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimhistory',
            name='party',
            field=models.CharField(choices=[('client', 'Клиент'), ('agency', 'Аутсорсинг'), ('promo', 'Вендоры'), ('broker', 'Кредитный брокер')], max_length=8, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='claimmessage',
            name='party',
            field=models.CharField(choices=[('client', 'Клиент'), ('agency', 'Аутсорсинг'), ('promo', 'Вендоры'), ('broker', 'Кредитный брокер')], max_length=8, verbose_name='Тип'),
        ),
    ]
