# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180717_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemployee',
            name='last_external_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление через API'),
        ),
    ]
