# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-17 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_agencyemployee_last_external_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeevent',
            options={'ordering': ['-id'], 'verbose_name': 'Кадровое мероприятие', 'verbose_name_plural': 'Кадровые мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='employeehistory',
            options={'ordering': ['-id'], 'verbose_name': 'Подтверждение кадрового мероприятия', 'verbose_name_plural': 'Подтверждения кадрового мероприятия'},
        ),
    ]
