# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20180817_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeehistory',
            options={'ordering': ['-id'], 'verbose_name': 'Подтверждение кадрового мероприятия', 'verbose_name_plural': 'Подтверждение кадрового мероприятия'},
        ),
    ]
