# Generated by Django 2.0.5 on 2018-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20180821_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='recruitment_state',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='active', max_length=8, verbose_name='Статус регистрации'),
        ),
    ]
