# Generated by Django 2.0.5 on 2018-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeehistory_recruitment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevent',
            name='kind',
            field=models.CharField(choices=[('recruitment', 'Recruitment'), ('dismissal', 'Dismissal'), ('change', 'Change'), ('agency', 'Agency')], max_length=16, verbose_name='Вид'),
        ),
    ]
