# Generated by Django 2.0.5 on 2018-09-20 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20180918_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('code', models.CharField(max_length=250, unique=True, verbose_name='Код')),
                ('sort_key', models.IntegerField(verbose_name='порядок отображения')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Справочник видов документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='С')),
                ('end', models.DateField(blank=True, null=True, verbose_name='По')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Образец документа')),
                ('comments', models.CharField(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('agency_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.AgencyEmployee', verbose_name='Сотрудник')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.DocType', verbose_name='Вид документа')),
            ],
            options={
                'verbose_name': 'Документ сотрудника',
                'verbose_name_plural': 'Документы сотрудников',
                'ordering': ['-id'],
            },
        ),
    ]
