"""
Copyright 2018 ООО «Верме»

Миграция базы данных приложения employees
"""

# Generated by Django 2.0.5 on 2018-10-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0105_auto_20181002_1756'),
        ('employees', '0009_doctype_employeedoc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orghistory',
            unique_together={('number', 'headquater', 'organization', 'start', 'agency_employee')},
        ),
    ]
