# Generated by Django 2.0.5 on 2018-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20181009_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyemployee',
            name='number',
            field=models.CharField(max_length=250, verbose_name='Табельный номер сотрудника в агентстве'),
        ),
        migrations.AlterField(
            model_name='agencyhistory',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='agencyhistory',
            name='start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
