# Generated by Django 2.0.5 on 2019-03-06 15:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20181031_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevent',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Параметры'),
        ),
    ]
