# Generated by Django 2.0.5 on 2019-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employeeevent_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedoc',
            name='dt_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='employeedoc',
            name='has_files',
            field=models.BooleanField(default=False, verbose_name='Наличие файлов'),
        ),
    ]
