# Generated by Django 2.0.5 on 2019-05-14 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0014_auto_20190410_1908'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM employees_agencyhistory"),
        migrations.RunSQL(
            "INSERT INTO employees_agencyhistory (agency_employee_id, agency_id, start, \"end\") "
            "SELECT id, agency_id, receipt, dismissal FROM employees_agencyemployee;"),
    ]
