# Generated by Django 2.0.5 on 2019-05-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_auto_20190514_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyhistory',
            name='agency_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ae_history', to='employees.AgencyEmployee'),
        ),
    ]
