# Generated by Django 2.0.5 on 2019-06-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20190520_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyhistory',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Agency', verbose_name='Агентство'),
        ),
        migrations.AlterField(
            model_name='agencyhistory',
            name='agency_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_history', to='employees.AgencyEmployee'),
        ),
    ]
