# Generated by Django 2.0.5 on 2019-06-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0137_remove_agency_manager'),
        ('employees', '0017_agencymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencymanager',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outsource.Agency', verbose_name='Агентство'),
        ),
    ]
