# Generated by Django 2.0.5 on 2019-06-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20190619_1057'),
        ('employees', '0018_agencymanager_agency'),
    ]

    operations = [
    ]
