# Generated by Django 2.0.5 on 2019-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_merge_20190619_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghistory',
            name='is_inactive',
            field=models.BooleanField(default=False, verbose_name='Неактивен (проходит обучение)'),
        ),
    ]
