# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_slug', models.SlugField(verbose_name='Template slug')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Параметры, передаваемые в сообщение', verbose_name='Параметры')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'В ожидании'), (1, 'Идет отправка'), (2, 'Отправлено'), (3, 'Пропуск'), (4, 'Ошибка')], default=0, verbose_name='Статус')),
                ('send_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('by_choice', 'По выбору сотрудника')], default='email', max_length=10)),
                ('error_text', models.TextField(blank=True, default='', max_length=500, verbose_name='Ошибка отправления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Очередь оповещения',
                'verbose_name_plural': 'Очередь оповещений',
                'db_table': 'notification_items',
            },
        ),
    ]
