# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_update_email_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifyitem',
            name='user',
        ),
    ]
