# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='код')),
                ('party', models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент')], max_length=8, verbose_name='тип')),
                ('icon', models.CharField(default='warning', help_text='название со страницы https://fortawesome.github.io/Font-Awesome/icons/', max_length=64, verbose_name='иконка')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('disabled', models.BooleanField(default=False, verbose_name='страница неактивна')),
                ('sort_key', models.IntegerField(verbose_name='порядок отображения')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
