# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.AddField(
            model_name='page',
            name='ext_name',
            field=models.TextField(blank=True, verbose_name='длинное название'),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission.Page', verbose_name='страница'),
        ),
    ]
