# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0094_headquater_party'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0002_auto_20180820_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', gfklookupwidget.fields.GfkLookupField(verbose_name='объект')),
                ('headquater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_prof_to_headquater', to='outsource.Headquater', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='код')),
                ('party', models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент')], max_length=8, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read', 'Чтение'), ('write', 'Запись')], default='read', max_length=8, verbose_name='действие')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.Page', verbose_name='страница')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.AccessRole', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.AccessRole', verbose_name='роль'),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='тип объекта'),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_prof_to_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
