# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_auto_20180821_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessprofile',
            options={'verbose_name': 'Права доступа', 'verbose_name_plural': 'Права доступа'},
        ),
    ]
