# Generated by Django 2.0.5 on 2018-08-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_create_promo_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='unit_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'outsource'), ('model', 'agency')), models.Q(('app_label', 'outsource'), ('model', 'organization')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='тип объекта'),
        ),
    ]
