# Generated by Django 2.0.5 on 2018-08-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0009_auto_20180829_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrole',
            name='party',
            field=models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент'), ('promo', 'Промоутер')], max_length=8, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='page',
            name='party',
            field=models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент'), ('promo', 'Промоутер')], max_length=8, verbose_name='тип'),
        ),
    ]
