# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 14:20
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def insert_pages_indo_db(apps, schema_editor):
    call_command('init_db')
    page_list = [('promo_create_employee', 'promo_employees_list'),
                 ('promo_edit_employee', 'promo_employees_list'),
                 ('promo_claim', 'promo_claims_list'),
                 ]
    Page = apps.get_model("permission", "Page")
    for page in Page.objects.filter(party='promo'):
        for lp in page_list:
            if page.code in lp[0]:
                parent_page = Page.objects.filter(code=lp[1], party=page.party, parent__isnull=True).first()
                if not parent_page:
                    continue
                page.parent_id = parent_page.id
                page.save(update_fields=['parent_id'])
                print ("Binded page", page.code, page.party, "to", parent_page.code, parent_page.party)
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0010_auto_20180829_1550'),
    ]

    operations = [
        migrations.RunPython(insert_pages_indo_db),
    ]