# Generated by Django 2.0.5 on 2018-10-01 14:59

from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0011_bind_promo_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='unit_id',
            field=gfklookupwidget.fields.GfkLookupField(verbose_name='орг. единица'),
        ),
        migrations.AlterField(
            model_name='accessprofile',
            name='unit_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'outsource'), ('model', 'agency')), models.Q(('app_label', 'outsource'), ('model', 'organization')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='тип орг. единицы'),
        ),
    ]
