# Generated by Django 2.0.5 on 2018-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0012_auto_20181001_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(choices=[('employees_list', 'employees_list'), ('create_employee', 'create_employee'), ('edit_employee', 'edit_employee'), ('hq_employees_list', 'hq_employees_list'), ('hq_edit_employee', 'hq_edit_employee'), ('promo_employees_list', 'promo_employees_list'), ('promo_create_employee', 'promo_create_employee'), ('promo_edit_employee', 'promo_edit_employee'), ('claims_list', 'claims_list'), ('claim', 'claim'), ('claim_frame', 'claim_frame'), ('hq_claims_list', 'hq_claims_list'), ('hq_claim', 'hq_claim'), ('promo_claims_list', 'promo_claims_list'), ('promo_claim', 'promo_claim'), ('shifts_list', 'shifts_list'), ('shifts_confirm', 'shifts_confirm'), ('hq_shifts_list', 'hq_shifts_list'), ('hq_shifts_confirm', 'hq_shifts_confirm'), ('requests_list', 'requests_list'), ('hq_requests_list', 'hq_requests_list'), ('hq_quotas_list', 'hq_quotas_list'), ('promo_schedule', 'promo_schedule')], max_length=32, verbose_name='код'),
        ),
    ]
