# Generated by Django 2.0.5 on 2018-11-02 16:29

import apps.lib.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0013_auto_20181030_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='code',
            field=apps.lib.forms.PageChoiceField(max_length=21, verbose_name='код'),
        ),
    ]
