# Generated by Django 2.0.5 on 2019-01-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0014_auto_20181102_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrole',
            name='party',
            field=models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент'), ('promo', 'Промоутер'), ('broker', 'Кредитный брокер')], max_length=8, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='page',
            name='party',
            field=models.CharField(choices=[('agency', 'Агентство'), ('client', 'Клиент'), ('promo', 'Промоутер'), ('broker', 'Кредитный брокер')], max_length=8, verbose_name='тип'),
        ),
    ]
