# Generated by Django 2.0.5 on 2019-01-10 08:22

import apps.lib.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0015_auto_20190110_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='code',
            field=apps.lib.forms.PageChoiceField(max_length=22, verbose_name='код'),
        ),
    ]
