# Generated by Django 2.0.5 on 2019-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0016_auto_20190110_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='страница скрыта'),
        ),
    ]
