# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 14:20
from __future__ import unicode_literals

from django.db import migrations

def hide_pages(apps, schema_editor):
    Page = apps.get_model("permission", "Page")
    for page in Page.objects.filter(parent__isnull=False):
        page.is_hidden = True
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0017_page_is_hidden'),
    ]

    operations = [
        migrations.RunPython(hide_pages),
    ]