# Generated by Django 2.0.5 on 2019-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0018_hide_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_changer_mode',
            field=models.CharField(choices=[('disabled', 'Отключен'), ('month', 'Месяц'), ('week', 'Неделя')], default='disabled', max_length=8, verbose_name='переключатель периодов'),
        ),
    ]
